# $Id: Makefile.defs,v 1.2 2006/05/06 15:18:39 leavens Exp $

ifndef TEXINPUTS
LATEXDIR=$(HOME)/LaTeX
ifeq ($(wildcard ${LATEXDIR}/*.tex),)
  LATEXDIR=$(HOME)/pkg/LaTeX
endif

TEXINPUTS=$(LATEXDIR)//:
endif

# End of file
