// This file was generated by jmlunit on Mon Nov 09 14:16:52 GMT 2009.

package election.tally;

/** Automatically-generated test driver for JML and JUnit based
 * testing of Decision. The superclass of this class should be edited
 * to supply test data. However it's best not to edit this class
 * directly; instead use the command
 * <pre>
 *  jmlunit Decision.java
 * </pre>
 * to regenerate this class whenever Decision.java changes.
 */
public class Decision_JML_Test
     extends Decision_JML_TestData
{
    /** Initialize this class. */
    public Decision_JML_Test(java.lang.String name) {
        super(name);
    }

    /** Run the tests. */
    public static void main(java.lang.String[] args) {
        org.jmlspecs.jmlunit.JMLTestRunner.run(suite());
        // You can also use a JUnit test runner such as:
        // junit.textui.TestRunner.run(suite());
    }

    /** Test to see if the code for class Decision
     * has been compiled with runtime assertion checking (i.e., by jmlc).
     * Code that is not compiled with jmlc would not make an effective test,
     * since no assertion checking would be done. */
    public void test$IsRACCompiled() {
        junit.framework.Assert.assertTrue("code for class Decision"
                + " was not compiled with jmlc"
                + " so no assertions will be checked!",
            org.jmlspecs.jmlrac.runtime.JMLChecker.isRACCompiled(Decision.class)
            );
    }

    /** Return the test suite for this test class.  This will have
    * added to it at least test$IsRACCompiled(), and any test methods
    * written explicitly by the user in the superclass.  It will also
    * have added test suites for each testing each method and
    * constructor.
    */
    //@ ensures \result != null;
    public static junit.framework.Test suite() {
        Decision_JML_Test testobj
            = new Decision_JML_Test("Decision_JML_Test");
        junit.framework.TestSuite testsuite = testobj.overallTestSuite();
        // Add instances of Test found by the reflection mechanism.
        testsuite.addTestSuite(Decision_JML_Test.class);
        testobj.addTestSuiteForEachMethod(testsuite);
        return testsuite;
    }

    /** A JUnit test object that can run a single test method.  This
     * is defined as a nested class solely for convenience; it can't
     * be defined once and for all because it must subclass its
     * enclosing class.
     */
    protected static abstract class OneTest extends Decision_JML_Test {

        /** Initialize this test object. */
        public OneTest(String name) {
            super(name);
        }

        /** The result object that holds information about testing. */
        protected junit.framework.TestResult result;

        //@ also
        //@ requires result != null;
        public void run(junit.framework.TestResult result) {
            this.result = result;
            super.run(result);
        }

        /* Run a single test and decide whether the test was
         * successful, meaningless, or a failure.  This is the
         * Template Method pattern abstraction of the inner loop in a
         * JML/JUnit test. */
        public void runTest() throws java.lang.Throwable {
            try {
                // The call being tested!
                doCall();
            }
            catch (org.jmlspecs.jmlrac.runtime.JMLEntryPreconditionError e) {
                // meaningless test input
                addMeaningless();
            } catch (org.jmlspecs.jmlrac.runtime.JMLAssertionError e) {
                // test failure
                int l = org.jmlspecs.jmlrac.runtime.JMLChecker.getLevel();
                org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel
                    (org.jmlspecs.jmlrac.runtime.JMLOption.NONE);
                try {
                    java.lang.String failmsg = this.failMessage(e);
                    junit.framework.AssertionFailedError err
                        = new junit.framework.AssertionFailedError(failmsg);
                    err.setStackTrace(new java.lang.StackTraceElement[]{});
                    err.initCause(e);
                    result.addFailure(this, err);
                } finally {
                    org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel(l);
                }
            } catch (java.lang.Throwable e) {
                // test success
            }
        }

        /** Call the method to be tested with the appropriate arguments. */
        protected abstract void doCall() throws java.lang.Throwable;

        /** Format the error message for a test failure, based on the
         * method's arguments. */
        protected abstract java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e);

        /** Inform listeners that a meaningless test was run. */
        private void addMeaningless() {
            if (result instanceof org.jmlspecs.jmlunit.JMLTestResult) {
                ((org.jmlspecs.jmlunit.JMLTestResult)result)
                    .addMeaningless(this);
            }
        }
    }

    /** Create the tests that are to be run for testing the class
     * Decision.  The framework will then run them.
     * @param overallTestSuite$ The suite accumulating all of the tests
     * for this driver class.
     */
    //@ requires overallTestSuite$ != null;
    public void addTestSuiteForEachMethod
        (junit.framework.TestSuite overallTestSuite$)
    {
        try {
            this.addTestSuiteFor$TestSetCandidate(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetCountNumber(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetDecisionType(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetDecisionStatus(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetCandidateID(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetCountNumber(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestCopy(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
    }

    /** Add tests for the setCandidate method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetCandidate
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setCandidate");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("setCandidate", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"setCandidate\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.LongIterator
                    vlong$1$iter
                    = this.vlongIter("setCandidate", 0);
                this.check_has_data
                    (vlong$1$iter,
                     "this.vlongIter(\"setCandidate\", 0)");
                while (!vlong$1$iter.atEnd()) {
                    final election.tally.Decision receiver$
                        = (election.tally.Decision) receivers$iter.get();
                    final long candidateIDValue
                        = vlong$1$iter.getLong();
                    methodTests$.addTest
                        (new TestSetCandidate(receiver$, candidateIDValue));
                    vlong$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setCandidate method. */
    protected static class TestSetCandidate extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;
        /** Argument candidateIDValue */
        private long candidateIDValue;

        /** Initialize this instance. */
        public TestSetCandidate(election.tally.Decision receiver$, long candidateIDValue) {
            super("setCandidate"+ ":" + candidateIDValue);
            this.receiver$ = receiver$;
            this.candidateIDValue = candidateIDValue;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setCandidate(candidateIDValue);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setCandidate' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument candidateIDValue: " + this.candidateIDValue;
            return msg;
        }
    }

    /** Add tests for the setCountNumber method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetCountNumber
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setCountNumber");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("setCountNumber", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"setCountNumber\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.LongIterator
                    vlong$1$iter
                    = this.vlongIter("setCountNumber", 0);
                this.check_has_data
                    (vlong$1$iter,
                     "this.vlongIter(\"setCountNumber\", 0)");
                while (!vlong$1$iter.atEnd()) {
                    final election.tally.Decision receiver$
                        = (election.tally.Decision) receivers$iter.get();
                    final long countNumberValue
                        = vlong$1$iter.getLong();
                    methodTests$.addTest
                        (new TestSetCountNumber(receiver$, countNumberValue));
                    vlong$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setCountNumber method. */
    protected static class TestSetCountNumber extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;
        /** Argument countNumberValue */
        private long countNumberValue;

        /** Initialize this instance. */
        public TestSetCountNumber(election.tally.Decision receiver$, long countNumberValue) {
            super("setCountNumber"+ ":" + countNumberValue);
            this.receiver$ = receiver$;
            this.countNumberValue = countNumberValue;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setCountNumber(countNumberValue);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setCountNumber' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument countNumberValue: " + this.countNumberValue;
            return msg;
        }
    }

    /** Add tests for the setDecisionType method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetDecisionType
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setDecisionType");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("setDecisionType", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"setDecisionType\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.ByteIterator
                    vbyte$1$iter
                    = this.vbyteIter("setDecisionType", 0);
                this.check_has_data
                    (vbyte$1$iter,
                     "this.vbyteIter(\"setDecisionType\", 0)");
                while (!vbyte$1$iter.atEnd()) {
                    final election.tally.Decision receiver$
                        = (election.tally.Decision) receivers$iter.get();
                    final byte decisionType
                        = vbyte$1$iter.getByte();
                    methodTests$.addTest
                        (new TestSetDecisionType(receiver$, decisionType));
                    vbyte$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setDecisionType method. */
    protected static class TestSetDecisionType extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;
        /** Argument decisionType */
        private byte decisionType;

        /** Initialize this instance. */
        public TestSetDecisionType(election.tally.Decision receiver$, byte decisionType) {
            super("setDecisionType"+ ":" + decisionType);
            this.receiver$ = receiver$;
            this.decisionType = decisionType;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setDecisionType(decisionType);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setDecisionType' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument decisionType: " + this.decisionType;
            return msg;
        }
    }

    /** Add tests for the getDecisionStatus method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetDecisionStatus
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getDecisionStatus");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("getDecisionStatus", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"getDecisionStatus\", 0))");
            while (!receivers$iter.atEnd()) {
                final election.tally.Decision receiver$
                    = (election.tally.Decision) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetDecisionStatus(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getDecisionStatus method. */
    protected static class TestGetDecisionStatus extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;

        /** Initialize this instance. */
        public TestGetDecisionStatus(election.tally.Decision receiver$) {
            super("getDecisionStatus");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getDecisionStatus();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getDecisionStatus' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the getCandidateID method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetCandidateID
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getCandidateID");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("getCandidateID", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"getCandidateID\", 0))");
            while (!receivers$iter.atEnd()) {
                final election.tally.Decision receiver$
                    = (election.tally.Decision) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetCandidateID(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getCandidateID method. */
    protected static class TestGetCandidateID extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;

        /** Initialize this instance. */
        public TestGetCandidateID(election.tally.Decision receiver$) {
            super("getCandidateID");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getCandidateID();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getCandidateID' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the getCountNumber method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetCountNumber
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getCountNumber");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("getCountNumber", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"getCountNumber\", 0))");
            while (!receivers$iter.atEnd()) {
                final election.tally.Decision receiver$
                    = (election.tally.Decision) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetCountNumber(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getCountNumber method. */
    protected static class TestGetCountNumber extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;

        /** Initialize this instance. */
        public TestGetCountNumber(election.tally.Decision receiver$) {
            super("getCountNumber");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getCountNumber();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getCountNumber' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the copy method
     * to the overall test suite. */
    private void addTestSuiteFor$TestCopy
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("copy");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.velection_tally_DecisionIter("copy", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.velection_tally_DecisionIter(\"copy\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                    velection_tally_Decision$1$iter
                    = this.velection_tally_DecisionIter("copy", 0);
                this.check_has_data
                    (velection_tally_Decision$1$iter,
                     "this.velection_tally_DecisionIter(\"copy\", 0)");
                while (!velection_tally_Decision$1$iter.atEnd()) {
                    final election.tally.Decision receiver$
                        = (election.tally.Decision) receivers$iter.get();
                    final election.tally.Decision decision
                        = (election.tally.Decision) velection_tally_Decision$1$iter.get();
                    methodTests$.addTest
                        (new TestCopy(receiver$, decision));
                    velection_tally_Decision$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the copy method. */
    protected static class TestCopy extends OneTest {
        /** The receiver */
        private election.tally.Decision receiver$;
        /** Argument decision */
        private election.tally.Decision decision;

        /** Initialize this instance. */
        public TestCopy(election.tally.Decision receiver$, election.tally.Decision decision) {
            super("copy"+ ":" + (decision==null? "null" :"{election.tally.Decision}"));
            this.receiver$ = receiver$;
            this.decision = decision;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.copy(decision);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'copy' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument decision: " + this.decision;
            return msg;
        }
    }

    /** Check that the iterator is non-null and not empty. */
    private void
    check_has_data(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter,
                   String call)
    {
        if (iter == null) {
            junit.framework.Assert.fail(call + " returned null");
        }
        if (iter.atEnd()) {
            junit.framework.Assert.fail(call + " returned an empty iterator");
        }
    }

    /** Converts a char to a printable String for display */
    public static String charToString(char c) {
        if (c == '\n') {
            return "NL";
        } else if (c == '\r') {
            return "CR";
        } else if (c == '\t') {
            return "TAB";
        } else if (Character.isISOControl(c)) {
            int i = (int)c;
            return "\\u"
                    + Character.forDigit((i/2048)%16,16)
                    + Character.forDigit((i/256)%16,16)
                    + Character.forDigit((i/16)%16,16)
                    + Character.forDigit((i)%16,16);
        }
        return Character.toString(c);
    }
}
