# -*- makefile -*- mode for emacs
# @(#) $Id: Makefile,v 1.8 2005/12/20 05:02:56 leavens Exp $

# Copyright (C) 1998, 1999 Iowa State University

# This file is part of JML

# JML is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# JML is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with JML; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

#
# Developer's Makefile for testing JML specs
#

PACKAGE = org.jmlspecs.samples.jmlrefman

JAVAFILES = 	\
		Constraint \
		GhostLocals \
		Heavyweight \
                Invariant \
		ImplicitOld \
		IntHeap \
		InconsistentMethodSpec \
		InconsistentMethodSpec2 \
                Lightweight \
		RefineDemo \
		RefineDemo2 \
                SignalsClause \
		SumArrayLoop \


NAMESTOTEST =  	\
		RefineDemo \
		RefineDemo2 \
		SumArrayLoop \


include ../Make.CommonDefs
