/* Generated by org.multijava.util.testing.Main */

package org.jmlspecs.samples.prelimdesign;

/**
 * This class is automatically generated using 
 * org.multijava.util.testing.Main and is used to 
 * group a collection of JUnit tests for the local 
 * package and perhaps some subpackages. 
 */
public class TestSuite extends junit.framework.TestSuite {
    public TestSuite() {
        super();
    }

    public TestSuite( String name ) {
        super( name );
    }

    public static junit.framework.Test suite() {
        junit.framework.TestSuite suite = 
            new junit.framework.TestSuite() {
                    public String toString() { return TEST_DESC; }
                };
        suite.addTest( org.jmlspecs.samples.prelimdesign.Account_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.IntMathOps_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.IntMathOps2_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.IntMathOps4_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.PlusAccount_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.USMoney_JML_Test.suite() );
        suite.addTest( org.jmlspecs.samples.prelimdesign.Point2D_JML_Test.suite() );
        return suite;
    }

    public static final String TEST_DESC = 
        "Test suite for org.jmlspecs.samples.prelimdesign";
}
