#!/usr/bin/perl -p
# @(#)$Id: adjust-grammar-file,v 1.2 2006/07/17 23:29:43 leavens Exp $

# Copyright (C) 2004 Iowa State University

# This file is part of JML

# JML is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# JML is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with JML; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

# trim newlines (needed on cygwin)
s/\r//g;

# link grammar defs and uses
s/^<VAR>([^<]*)<\/VAR> ::=/<A NAME="$1"><VAR>$1<\/VAR><\/A> ::=/g;
s/ <VAR>([^<]*)<\/VAR>/ <A HREF="\#$1"><VAR>$1<\/VAR><\/A>/g;
s/^<var>([^<]*)<\/var> ::=/<a name="$1"><var>$1<\/var><\/a> ::=/g;
s/ <var>([^<]*)<\/var>/ <a href="\#$1"><var>$1<\/var><\/a>/g;


