// This file was generated by jmlunit on Tue May 20 17:38:47 EDT 2008.

package org.jmlspecs.jmlunit.strategies;

import java.util.NoSuchElementException;

/** Automatically-generated test driver for JML and JUnit based
 * testing of CompositeIterator. The superclass of this class should be edited
 * to supply test data. However it's best not to edit this class
 * directly; instead use the command
 * <pre>
 *  jmlunit CompositeIterator.java
 * </pre>
 * to regenerate this class whenever CompositeIterator.java changes.
 */
public class CompositeIterator_JML_Test
     extends CompositeIterator_JML_TestData
{
    /** Initialize this class. */
    public CompositeIterator_JML_Test(java.lang.String name) {
        super(name);
    }

    /** Run the tests. */
    public static void main(java.lang.String[] args) {
        org.jmlspecs.jmlunit.JMLTestRunner.run(suite());
        // You can also use a JUnit test runner such as:
        // junit.textui.TestRunner.run(suite());
    }

    /** Test to see if the code for class CompositeIterator
     * has been compiled with runtime assertion checking (i.e., by jmlc).
     * Code that is not compiled with jmlc would not make an effective test,
     * since no assertion checking would be done. */
    public void test$IsRACCompiled() {
        junit.framework.Assert.assertTrue("code for class CompositeIterator"
                + " was not compiled with jmlc"
                + " so no assertions will be checked!",
            org.jmlspecs.jmlrac.runtime.JMLChecker.isRACCompiled(CompositeIterator.class)
            );
    }

    /** Return the test suite for this test class.  This will have
    * added to it at least test$IsRACCompiled(), and any test methods
    * written explicitly by the user in the superclass.  It will also
    * have added test suites for each testing each method and
    * constructor.
    */
    //@ ensures \result != null;
    public static junit.framework.Test suite() {
        CompositeIterator_JML_Test testobj
            = new CompositeIterator_JML_Test("CompositeIterator_JML_Test");
        junit.framework.TestSuite testsuite = testobj.overallTestSuite();
        // Add instances of Test found by the reflection mechanism.
        testsuite.addTestSuite(CompositeIterator_JML_Test.class);
        testobj.addTestSuiteForEachMethod(testsuite);
        return testsuite;
    }

    /** A JUnit test object that can run a single test method.  This
     * is defined as a nested class solely for convenience; it can't
     * be defined once and for all because it must subclass its
     * enclosing class.
     */
    protected static abstract class OneTest extends CompositeIterator_JML_Test {

        /** Initialize this test object. */
        public OneTest(String name) {
            super(name);
        }

        /** The result object that holds information about testing. */
        protected junit.framework.TestResult result;

        //@ also
        //@ requires result != null;
        public void run(junit.framework.TestResult result) {
            this.result = result;
            super.run(result);
        }

        /* Run a single test and decide whether the test was
         * successful, meaningless, or a failure.  This is the
         * Template Method pattern abstraction of the inner loop in a
         * JML/JUnit test. */
        public void runTest() throws java.lang.Throwable {
            try {
                // The call being tested!
                doCall();
            }
            catch (org.jmlspecs.jmlrac.runtime.JMLEntryPreconditionError e) {
                // meaningless test input
                addMeaningless();
            } catch (org.jmlspecs.jmlrac.runtime.JMLAssertionError e) {
                // test failure
                int l = org.jmlspecs.jmlrac.runtime.JMLChecker.getLevel();
                org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel
                    (org.jmlspecs.jmlrac.runtime.JMLOption.NONE);
                try {
                    java.lang.String failmsg = this.failMessage(e);
                    junit.framework.AssertionFailedError err
                        = new junit.framework.AssertionFailedError(failmsg);
                    err.setStackTrace(new java.lang.StackTraceElement[]{});
                    err.initCause(e);
                    result.addFailure(this, err);
                } finally {
                    org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel(l);
                }
            } catch (java.lang.Throwable e) {
                // test success
            }
        }

        /** Call the method to be tested with the appropriate arguments. */
        protected abstract void doCall() throws java.lang.Throwable;

        /** Format the error message for a test failure, based on the
         * method's arguments. */
        protected abstract java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e);

        /** Inform listeners that a meaningless test was run. */
        private void addMeaningless() {
            if (result instanceof org.jmlspecs.jmlunit.JMLTestResult) {
                ((org.jmlspecs.jmlunit.JMLTestResult)result)
                    .addMeaningless(this);
            }
        }
    }

    /** Create the tests that are to be run for testing the class
     * CompositeIterator.  The framework will then run them.
     * @param overallTestSuite$ The suite accumulating all of the tests
     * for this driver class.
     */
    //@ requires overallTestSuite$ != null;
    public void addTestSuiteForEachMethod
        (junit.framework.TestSuite overallTestSuite$)
    {
        try {
            this.addTestSuiteFor$TestCompositeIterator(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestCompositeIterator$1(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestCompositeIterator$2(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestAtEnd(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGet(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestAdvance(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestClone(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestToString(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
    }

    /** Add tests for the CompositeIterator contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestCompositeIterator
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("CompositeIterator");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter
                = this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter("CompositeIterator", 0);
            this.check_has_data
                (vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter,
                 "this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter(\"CompositeIterator\", 0)");
            while (!vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter
                    = (org.jmlspecs.jmlunit.strategies.IndefiniteIterator) vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.get();
                methodTests$.addTest
                    (new TestCompositeIterator(iter));
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the CompositeIterator contructor. */
    protected static class TestCompositeIterator extends OneTest {
        /** Argument iter */
        private org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter;

        /** Initialize this instance. */
        public TestCompositeIterator(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter) {
            super("CompositeIterator"+ ":" + (iter==null? "null" :"{org.jmlspecs.jmlunit.strategies.IndefiniteIterator}"));
            this.iter = iter;
        }

        protected void doCall() throws java.lang.Throwable {
            new CompositeIterator(iter);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'CompositeIterator' applied to";
            msg += "\n\tArgument iter: " + this.iter;
            return msg;
        }
    }

    /** Add tests for the CompositeIterator contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestCompositeIterator$1
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("CompositeIterator");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter
                = this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter("CompositeIterator", 1);
            this.check_has_data
                (vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter,
                 "this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter(\"CompositeIterator\", 1)");
            while (!vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                    vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$2$iter
                    = this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter("CompositeIterator", 0);
                this.check_has_data
                    (vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$2$iter,
                     "this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIteratorIter(\"CompositeIterator\", 0)");
                while (!vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$2$iter.atEnd()) {
                    final org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter1
                        = (org.jmlspecs.jmlunit.strategies.IndefiniteIterator) vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.get();
                    final org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter2
                        = (org.jmlspecs.jmlunit.strategies.IndefiniteIterator) vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$2$iter.get();
                    methodTests$.addTest
                        (new TestCompositeIterator$1(iter1, iter2));
                    vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$2$iter.advance();
                }
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$1$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the CompositeIterator contructor. */
    protected static class TestCompositeIterator$1 extends OneTest {
        /** Argument iter1 */
        private org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter1;
        /** Argument iter2 */
        private org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter2;

        /** Initialize this instance. */
        public TestCompositeIterator$1(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter1, org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter2) {
            super("CompositeIterator"+ ":" + (iter1==null? "null" :"{org.jmlspecs.jmlunit.strategies.IndefiniteIterator}")+ "," +(iter2==null? "null" :"{org.jmlspecs.jmlunit.strategies.IndefiniteIterator}"));
            this.iter1 = iter1;
            this.iter2 = iter2;
        }

        protected void doCall() throws java.lang.Throwable {
            new CompositeIterator(iter1, iter2);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'CompositeIterator' applied to";
            msg += "\n\tArgument iter1: " + this.iter1;
            msg += "\n\tArgument iter2: " + this.iter2;
            return msg;
        }
    }

    /** Add tests for the CompositeIterator contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestCompositeIterator$2
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("CompositeIterator");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_$1$iter
                = this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_Iter("CompositeIterator", 0);
            this.check_has_data
                (vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_$1$iter,
                 "this.vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_Iter(\"CompositeIterator\", 0)");
            while (!vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_$1$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.IndefiniteIterator[] iters
                    = (org.jmlspecs.jmlunit.strategies.IndefiniteIterator[]) vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_$1$iter.get();
                methodTests$.addTest
                    (new TestCompositeIterator$2(iters));
                vorg_jmlspecs_jmlunit_strategies_IndefiniteIterator$_$1$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the CompositeIterator contructor. */
    protected static class TestCompositeIterator$2 extends OneTest {
        /** Argument iters */
        private org.jmlspecs.jmlunit.strategies.IndefiniteIterator[] iters;

        /** Initialize this instance. */
        public TestCompositeIterator$2(org.jmlspecs.jmlunit.strategies.IndefiniteIterator[] iters) {
            super("CompositeIterator"+ ":" + (iters==null?"null":("{org.jmlspecs.jmlunit.strategies.IndefiniteIterator["+iters.length + "]"+"}")));
            this.iters = iters;
        }

        protected void doCall() throws java.lang.Throwable {
            new CompositeIterator(iters);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'CompositeIterator' applied to";
            msg += "\n\tArgument iters: " + this.iters;
            return msg;
        }
    }

    /** Add tests for the atEnd method
     * to the overall test suite. */
    private void addTestSuiteFor$TestAtEnd
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("atEnd");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter("atEnd", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter(\"atEnd\", 0))");
            while (!receivers$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$
                    = (org.jmlspecs.jmlunit.strategies.CompositeIterator) receivers$iter.get();
                methodTests$.addTest
                    (new TestAtEnd(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the atEnd method. */
    protected static class TestAtEnd extends OneTest {
        /** The receiver */
        private org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$;

        /** Initialize this instance. */
        public TestAtEnd(org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$) {
            super("atEnd");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.atEnd();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'atEnd' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the get method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGet
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("get");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter("get", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter(\"get\", 0))");
            while (!receivers$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$
                    = (org.jmlspecs.jmlunit.strategies.CompositeIterator) receivers$iter.get();
                methodTests$.addTest
                    (new TestGet(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the get method. */
    protected static class TestGet extends OneTest {
        /** The receiver */
        private org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$;

        /** Initialize this instance. */
        public TestGet(org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$) {
            super("get");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.get();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'get' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the advance method
     * to the overall test suite. */
    private void addTestSuiteFor$TestAdvance
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("advance");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter("advance", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter(\"advance\", 0))");
            while (!receivers$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$
                    = (org.jmlspecs.jmlunit.strategies.CompositeIterator) receivers$iter.get();
                methodTests$.addTest
                    (new TestAdvance(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the advance method. */
    protected static class TestAdvance extends OneTest {
        /** The receiver */
        private org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$;

        /** Initialize this instance. */
        public TestAdvance(org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$) {
            super("advance");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.advance();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'advance' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the clone method
     * to the overall test suite. */
    private void addTestSuiteFor$TestClone
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("clone");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter("clone", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter(\"clone\", 0))");
            while (!receivers$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$
                    = (org.jmlspecs.jmlunit.strategies.CompositeIterator) receivers$iter.get();
                methodTests$.addTest
                    (new TestClone(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the clone method. */
    protected static class TestClone extends OneTest {
        /** The receiver */
        private org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$;

        /** Initialize this instance. */
        public TestClone(org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$) {
            super("clone");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.clone();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'clone' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the toString method
     * to the overall test suite. */
    private void addTestSuiteFor$TestToString
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("toString");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter("toString", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vorg_jmlspecs_jmlunit_strategies_CompositeIteratorIter(\"toString\", 0))");
            while (!receivers$iter.atEnd()) {
                final org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$
                    = (org.jmlspecs.jmlunit.strategies.CompositeIterator) receivers$iter.get();
                methodTests$.addTest
                    (new TestToString(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the toString method. */
    protected static class TestToString extends OneTest {
        /** The receiver */
        private org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$;

        /** Initialize this instance. */
        public TestToString(org.jmlspecs.jmlunit.strategies.CompositeIterator receiver$) {
            super("toString");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.toString();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'toString' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Check that the iterator is non-null and not empty. */
    private void
    check_has_data(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter,
                   String call)
    {
        if (iter == null) {
            junit.framework.Assert.fail(call + " returned null");
        }
        if (iter.atEnd()) {
            junit.framework.Assert.fail(call + " returned an empty iterator");
        }
    }

    /** Converts a char to a printable String for display */
    public static String charToString(char c) {
        if (c == '\n') {
            return "NL";
        } else if (c == '\r') {
            return "CR";
        } else if (c == '\t') {
            return "TAB";
        } else if (Character.isISOControl(c)) {
            int i = (int)c;
            return "\\u"
                    + Character.forDigit((i/2048)%16,16)
                    + Character.forDigit((i/256)%16,16)
                    + Character.forDigit((i/16)%16,16)
                    + Character.forDigit((i)%16,16);
        }
        return Character.toString(c);
    }
}
