/* Generated by org.multijava.util.testing.Main */

package org.jmlspecs.jmlunit.strategies;

/**
 * This class is automatically generated using 
 * org.multijava.util.testing.Main and is used to 
 * group a collection of JUnit tests for the local 
 * package and perhaps some subpackages. 
 */
public class TestSuite extends junit.framework.TestSuite {
    public TestSuite() {
        super();
    }

    public TestSuite( String name ) {
        super( name );
    }

    public static junit.framework.Test suite() {
        junit.framework.TestSuite suite = 
            new junit.framework.TestSuite() {
                    public String toString() { return TEST_DESC; }
                };
        suite.addTest( org.jmlspecs.jmlunit.strategies.CharIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.CloneableObjectArrayAbstractIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.CompositeIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.DoubleAbstractFilteringIteratorDecorator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.DoubleCompositeIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.ImmutableObjectArrayIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.IntArrayIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.NewObjectAbstractIterator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator_JML_Test.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.ByteStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.ShortStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.IntStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.LongStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.FloatStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.DoubleStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.CharStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.BooleanStrategyTypeTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.StringStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.ObjectStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.ImmutableObjectAbstractStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.CloneableObjectAbstractStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.NewObjectAbstractStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.CompositeStrategyTest.suite() );
        suite.addTest( org.jmlspecs.jmlunit.strategies.NonNullStrategyDecoratorTest.suite() );
        return suite;
    }

    public static final String TEST_DESC = 
        "Test suite for org.jmlspecs.jmlunit.strategies";
}
